# Generated by Django 4.0.5 on 2022-06-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('context', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_img/')),
                ('bio', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('projects', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
