# Generated by Django 4.0.5 on 2022-06-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_project_title_project_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
