# Generated by Django 4.0.5 on 2022-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_project_content_project_design_project_usability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='profilesadded',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='project_img/'),
        ),
    ]
