# Generated by Django 4.0.5 on 2022-06-15 12:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profile_profile_pic_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesadded',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, verbose_name='image'),
        ),
    ]
