# Generated by Django 4.0.5 on 2022-06-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_profile_profile_pic_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='user',
        ),
    ]
