# Generated by Django 4.0.5 on 2022-06-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_author_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='context',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
