# Generated by Django 4.0.5 on 2022-06-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_project_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='user',
        ),
    ]
